version: '3.2'
services:
  nginx:
    image: nginx
    volumes:
      - ./server/docker/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./client:/var/www/app
    ports:
      - 8000:80
    depends_on:
      - server

  server:
    build:
      context: ./server/docker
      dockerfile: Dockerfile
    env_file:
      - ".env"
    volumes:
      - ./server:/var/www/app


  client:
    volumes:
      - ./client:/var/www/app
      - /var/www/app/node_modules
    ports:
      - 3000:3000

  mysql:
    image: mysql:5.7.22
    command: "--innodb_use_native_aio=0"
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  myadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=${MYSQL_HOST}


